### PR TITLE
Add exception for route

### PR DESCRIPTION
**Pull request by djKooks**
Hello
During study with akka-http, it seems it can setup exception for router, so maybe it could be good for sample. I'm not quite good in akka yet, so if there is any problem, please let me know.

Thanks.

### CODE REVIEW

**Comment by ktoso** [comment]
Akka HTTP renders such 500 responses automatically. Not sure this needs to be shown like this in the QuickStart

**Comment by djKooks** [comment]
@ktoso oh, thanks for suggestion~
Regardless of this PR, I think it would be good to add handle exception for sample. Is there some kind of guide documents about it?

**Comment by ktoso** [comment]
This is a quick start, not the full documentation. It should contain the bare minimum, and I do not think we need teach the exception handlers here. 

They are properly documented in https://doc.akka.io/docs/akka-http/current/routing-dsl/exception-handling.html

Thanks for the PR but for this specific thing I’d like to rely to the full reference documentation to introduce this concept.

**Comment by djKooks** [comment]
@ktoso okay. Appreciate for your help!

**Pull request closed without merging**
