### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by thothmoses**
References #xxxx

### CODE REVIEW

**Comment by thothmoses** [comment]
@andreaTP @patriknw Can you review and figure out why this is not building?

**Comment by jrudolph** [comment]
What is this about?

**Comment by thothmoses** [comment]
@jrudolph this is in regard TO https://github.com/akka/akka-quickstart-scala.g8/issues/61

**Review by johanandren — APPROVED** [review]

**Comment by thothmoses** [comment]
@ignasi can you take a look at this I cannot get this to pass the checks.

**Comment by johanandren** [comment]
It's the same issue with jabba as elsewhere, I've [PR:ed a fix](https://github.com/akka/akka-http-quickstart-scala.g8/pull/84) to switch away from jabba. 

This is just the README though so should be fine to merge without validation passing.

**Comment by thothmoses** [comment]
@johanandren Thanks for the info - I don't have permission. to force the merge. Could you do it. Thanks in advance.

**Pull request merged**
